spring:
  application:
   name: chatAPI
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: 12345678

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

